language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
env:
  - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/tests:$TRAVIS_BUILD_DIR/src/main/common
script:
  - cd src/main/common
  - python util.py
  - cd ../../test/common
  - coverage run -m unittest discover
  - coverage report -m
after_success:
  - coveralls
