language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - echo 'export PYTHONPATH="/home/travis/build/DarrenAscione/epic-testbed/src/main/common"' >>~/.bash_profile
  - cd src/main/common
  - python util.py
  - cd ../../test/common
  - python -c "import sys; print(sys.path)"
  - coverage run test_util.py
  - coverage report
after_success:
  - coveralls
