language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
env:
  - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/tests:$TRAVIS_BUILD_DIR/src/main/common
script:
  - cd src/main/common
  - python util.py
  - cd ../../test/common
  - coverage run test_util.py
  - coverage report
after_success:
  - coveralls
