language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - python setup.py
  - python -c "import sys; print(sys.path)"
  - cd src/main/common
  - pwd
  - python util.py
  - cd ../../test/common
  - python -c "import sys; print(sys.path)"
  - coverage run test_util.py
  - coverage report
after_success:
  - coveralls
